### PR TITLE
fix(docker-entrypoint-initdb): bump wait timeout

### LINKED ISSUE #56: deis/postgres dying halfway through restore
~~This seems like an upstream kubernetes issue: https://github.com/kubernetes/kubernetes/issues/7891#issuecomment-191886569~~

~~I guess the crutch solution is to remove the `readiness` probe and let the database handle its own health checks, or find a way for readinessProbes to work with postgres that won't end up killing the pod.~~

Just looks like the container is being killed off:

```
LOG:  database system was shut down in recovery at 2016-03-03 17:26:33 UTC
LOG:  starting archive recovery
FATAL:  the database system is starting up
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-fetch".
        STRUCTURED: time=2016-03-03T17:26:49.210204-00 pid=363
wal_e.operator.backup INFO     MSG: begin wal restore
        STRUCTURED: time=2016-03-03T17:26:56.443877-00 pid=363 action=wal-fetch key=s3://kents-database/wal_005/000000010000000000000003.lzo prefix= seg=000000010000000000000003 state=begin
wal_e.blobstore.s3.calling_format INFO     MSG: connecting to S3 with creds (<botocore.credentials.Credentials object at 0x7f735b0faad0>)
        STRUCTURED: time=2016-03-03T17:26:56.573421-00 pid=363
botocore.credentials INFO     Found credentials in environment variables.
FATAL:  the database system is starting up
boto3.resources.action INFO     Calling s3:get_object with {u'Bucket': 'kents-database', u'Key': 'wal_005/000000010000000000000003.lzo'}
botocore.vendored.requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): kents-database.s3.amazonaws.com
wal_e.blobstore.s3.s3_util INFO     MSG: completed download and decompression
        DETAIL: Downloaded and decompressed "s3://kents-database/wal_005/000000010000000000000003.lzo" to "pg_xlog/RECOVERYXLOG"
        STRUCTURED: time=2016-03-03T17:27:12.595790-00 pid=363
wal_e.operator.backup INFO     MSG: complete wal restore
        STRUCTURED: time=2016-03-03T17:27:12.878355-00 pid=363 action=wal-fetch key=s3://kents-database/wal_005/000000010000000000000003.lzo prefix= seg=000000010000000000000003 state=complete
LOG:  restored log file "000000010000000000000003" from archive
LOG:  redo starts at 0/3000090
LOG:  consistent recovery state reached at 0/4000000
FATAL:  the database system is starting up
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-fetch".
        STRUCTURED: time=2016-03-03T17:27:29.382059-00 pid=427
wal_e.operator.backup INFO     MSG: begin wal restore
        STRUCTURED: time=2016-03-03T17:27:35.576663-00 pid=427 action=wal-fetch key=s3://kents-database/wal_005/000000010000000000000004.lzo prefix= seg=000000010000000000000004 state=begin
wal_e.blobstore.s3.calling_format INFO     MSG: connecting to S3 with creds (<botocore.credentials.Credentials object at 0x7f151eb1aad0>)
        STRUCTURED: time=2016-03-03T17:27:35.697055-00 pid=427
botocore.credentials INFO     Found credentials in environment variables.
LOG:  server process (PID 221) exited with exit code 2
LOG:  terminating any other active server processes
FATAL:  could not restore file "000000010000000000000004" from archive: child process was terminated by signal 3: Quit
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted while in recovery at log time 2016-03-03 16:42:36 UTC
HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
LOG:  starting archive recovery
LOG:  startup process (PID 489) was terminated by signal 9: Killed
LOG:  aborting startup due to startup process failure
```

### PR DESCRIPTION
**Pull request by bacongobbler**
The default wait time is 1 minute, which usually isn't enough time
for a recovery to finish. Bumping to 20 minutes seems to alleviate
the problem. We're not entirely sure why.

closes #56

### CODE REVIEW

**Comment by bacongobbler** [comment]
I tested this manually with minio to verify:

```
helm install deis-dev
deis register http://deis.$DEIS_TEST_DOMAIN --username bacongobbler --password pass --email mfisher@deis.com
deis keys:add ~/.ssh/id_rsa.pub
for i in $(seq 1 100); do deis create foo-$i --no-remote &>/dev/null; done
kubectl --namespace=deis delete pod deis-database-asdf12
# wait a bit for the database and workflow to come back up
deis apps | grep -v "=== Apps" | wc -l
100
```

File: rootfs/docker-entrypoint-initdb.d/003_restore_from_backup.sh [hunk 1]
```diff
@@ -46,6 +46,7 @@ EOF
   echo "restore_command = 'envdir /etc/wal-e.d/env wal-e wal-fetch \"%f\" \"%p\"'" >> "$PGDATA/recovery.conf"
   gosu postgres pg_ctl -D "$PGDATA" \
       -o "-c listen_addresses=''" \
+      -t 300 \
```
Comment (krancour) [inline rootfs/docker-entrypoint-initdb.d/003_restore_from_backup.sh]: I'm not sure this is long enough.

Comment (krancour) [inline rootfs/docker-entrypoint-initdb.d/003_restore_from_backup.sh]: At least not with s3.

Comment (bacongobbler) [inline rootfs/docker-entrypoint-initdb.d/003_restore_from_backup.sh]: 15 minutes? What would be a decent recovery timeout?

Comment (bacongobbler) [inline rootfs/docker-entrypoint-initdb.d/003_restore_from_backup.sh]: bumped to 20 minutes

**Comment by jchauncey** [comment]
Seeing the following: 

```
        DETAIL: The subcommand is "wal-fetch".
        STRUCTURED: time=2016-03-08T03:21:32.782932-00 pid=5109
FATAL:  the database system is starting up
.wal_e.operator.backup INFO     MSG: promoted prefetched wal segment
        STRUCTURED: time=2016-03-08T03:21:33.024814-00 pid=5109 action=wal-fetch key=s3://dbwal/wal_005/0000000100000000000000F6.lzo prefix= seg=0000000100000000000000F6
LOG:  restored log file "0000000100000000000000F6" from archive
FATAL:  the database system is starting up
.wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-fetch".
        STRUCTURED: time=2016-03-08T03:21:34.110124-00 pid=5126
wal_e.operator.backup INFO     MSG: promoted prefetched wal segment
        STRUCTURED: time=2016-03-08T03:21:34.393374-00 pid=5126 action=wal-fetch key=s3://dbwal/wal_005/0000000100000000000000F7.lzo prefix= seg=0000000100000000000000F7
LOG:  restored log file "0000000100000000000000F7" from archive
FATAL:  the database system is starting up
```

**Comment by bacongobbler** [comment]
@jchauncey that is actually an expected (but not really) error. `-w` makes us wait for the database to start up. When in recovery it is not considered ready to accept connections so it'll output those errors as FATAL... Even though in our case it isn't. I'll have to fix that up in the future.

**Comment by bacongobbler** [comment]
Just give it a little longer to recover :)

**Comment by jchauncey** [comment]
this has been going for over an hour and im still getting that error.

**Comment by bacongobbler** [comment]
Okay so then this does not fix #56.

File: rootfs/docker-entrypoint-initdb.d/003_restore_from_backup.sh (hunk 1 above)
Comment (krancour) [inline rootfs/docker-entrypoint-initdb.d/003_restore_from_backup.sh]: :+1:

**Comment by krancour** [comment]
I know @jchauncey said he's still having trouble with this, but I've manually tested this with good results.  That being said, long-running recoveries could still be problematic.  See #53, which, when fixed, would help alleviate that a bit.  I think even if this is not perfect, it's such a significant improvement that it LGTM.

**Comment by jchauncey** [comment]
Ok so this eventually recovered during the night. Definitely took a while
